### ISSUE TITLE
Italian Translation for "open menu"

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/juridica#12]
Apparently the translation is wrong it's currently "apri menu" and should be "manu aperto" as mentioned by a user here: http://themeisle.com/forums/topic/child-theme-juridica-italian-traslation/

@rodica-andronache In these cases what would we do? I have every limited knowledge on how WordPress translation works so would we be able to ask the user to help us translate the theme to italian or something? How would we do that?

**Comment by rodica-andronache** [comment]
@UVLabs in the theme, all the translations are here for juridica:
https://translate.wordpress.org/projects/wp-themes/juridica
If the user wants to change or add a translation for one of the strings , i think he only needs an account on wp.org and change it there. But after that, an admin editor, or something like this, should approve that change. If you want more details about how this works, I think the best suited to answer is Marius Ghitulescu.
So, I'm gonna close this ticket as it doesn't have something to do with the theme :D
